### ISSUE TITLE
Issues with Shuttle API's get_vehicle_route_stop_estimates

### ISSUE THREAD

**Issue by azharichenko** [Pitt-CSC/PittAPI#103]
Recently the builds are showing an issue with Shuttle API's `get_vehicle_route_stop_estimates` and this should be investigated.

The issue comming off is....
```python
======================================================================
ERROR: test_vehicle_route_stop_estimates (tests.shuttle_test.ShuttleTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "<string>", line 3, in wrapper
  File "/home/travis/build/Pitt-CSC/PittAPI/tests/shuttle_test.py", line 55, in test_vehicle_route_stop_estimates
    stop_estimates = shuttle.get_vehicle_route_stop_estimates(25, 4)
  File "/home/travis/build/Pitt-CSC/PittAPI/PittAPI/shuttle.py", line 43, in get_vehicle_route_stop_estimates
    response = sess.get("http://www.pittshuttle.com/Services/JSONPRelay.svc/GetVehicleRouteStopEstimates", params=payload)
  File "/home/travis/virtualenv/python3.4.6/lib/python3.4/site-packages/requests/sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "/home/travis/virtualenv/python3.4.6/lib/python3.4/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/travis/virtualenv/python3.4.6/lib/python3.4/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/travis/virtualenv/python3.4.6/lib/python3.4/site-packages/responses.py", line 625, in unbound_on_send
    return self._on_request(adapter, request, *a, **kwargs)
  File "/home/travis/virtualenv/python3.4.6/lib/python3.4/site-packages/responses.py", line 600, in _on_request
    raise response
requests.exceptions.ConnectionError: Connection refused: GET http://www.pittshuttle.com/Services/JSONPRelay.svc/GetVehicleRouteStopEstimates?vehicleIdStrings=25&quantity=4
````

**Comment by RitwikGupta** [comment]
Should be fixed with #105
